### PR TITLE
debug adding libzfp.so

### PR DESCRIPTION
**Pull request by halehawk**
First try to test on your travis CI.

### CODE REVIEW

**Comment by halehawk** [comment]
I didn't see travis  CI check, how can I start it? @lindstro2

**Comment by lindstro** [comment]
Not sure why the Travis build wasn't triggered.  Do you have it set up on your fork?  See this: https://travis-ci.community/t/pull-requests-from-forks-does-not-trigger-travis-ci/8393.

**Comment by halehawk** [comment]
@lindstro2, the updated config.sh makes the osx installation worked. The run_tests.py confirmed the wheel file correctly built and installed. Delocate will never work on your codes, it needs extra steps in your setup.py and need you add lib/python/ directory etc. I didn't want to change that much, so just modified config.sh.

**Comment by halehawk** [comment]
My .github/workflow/wheel.yml works on building wheel and link to libzfp.dylib on macos now.

**Pull request merged**
